config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  
  resources :users 
  resources :microposts 
  resources :follows
  resources :unfollowed 
  resources :sessions, only: [:new, :create, :destroy]

  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'micropost', to: 'microposts#index', as: 'posts'
  get 'follows', to: 'follows#index', as: 'follers'
  get 'landing', to: 'index#landing', as: 'landing'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/unfollowed_controller.rb
# frozen_string_literal: true

class UnfollowedController < ApplicationController
  before_action :logged_in_user, :auth_check, only: %i[index]

  def index
    @unfollowed_users = User.where.not(id: logged_in_user.id)
                            .where.not(id: Follow.select(:following_user_id).where(user_id: logged_in_user.id))
    # @unfollowed_users.followed = User.where.not(:id => logged_in_user.id)
    #                        .where.not(:id => Follow.select(:following_user_id).where(:user_id => logged_in_user.id))
  end
end

app/helpers/unfollowed_helper.rb
# frozen_string_literal: true

module UnfollowedHelper
end

app/views/unfollowed/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/unfollowed/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @unfollowed_user %>

<%= link_to 'Show', @unfollowed_user %> |
<%= link_to 'Back', users_path %>

app/views/unfollowed/index.html.erb
<h1>Unfollowed Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @unfollowed_users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Follow', follows_path(user), method: :POST %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'New User', new_user_path %> -->

<br>
<br>

<%= link_to 'Back', landing_path %>

app/views/unfollowed/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/unfollowed/show.html.erb
<h1>User</h1>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', landing_path %>