config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  
  resources :users 
  resources :microposts 
  resources :follows
  resources :unfollowed 
  resources :sessions, only: [:new, :create, :destroy]

  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'micropost', to: 'microposts#index', as: 'posts'
  get 'follows', to: 'follows#index', as: 'follers'
  get 'landing', to: 'index#landing', as: 'landing'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/follow.rb
# frozen_string_literal: true

class Follow < ApplicationRecord
  validates_presence_of :user_id
  validates_presence_of :following_user_id
  belongs_to :user
  belongs_to :user
end

app/controllers/follows_controller.rb
# frozen_string_literal: true

class FollowsController < ApplicationController
  before_action :set_follow, only: %i[show edit update destroy]
  before_action :logged_in_user, :auth_check

  # GET /follows or /follows.json
  def index
    @follows = Follow.where(following_user_id: logged_in_user.id)
    respond_to do |format|
      format.html { render }
      format.json { render json: @follows, each_serializer: FollowSerializer }
    end
  end

  # GET /follows/1 or /follows/1.json
  def show
  end

  # GET /follows/new
  def new
    @follow = Follow.new
    set_following
  end

  # GET /follows/1/edit
  def edit; end

  # POST /follows or /follows.json
  def create
    @follow = Follow.new
    set_following
    @follow.user_id = logged_in_user.id
    if @follow.save
      redirect_to unfollowed_index_path, notice: 'Followed successfully.'
    else
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @follow.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /follows/1 or /follows/1.json
  def update
    respond_to do |format|
      if @follow.update(follow_params)
        format.html { redirect_to @follow, notice: 'Follow was successfully updated.' }
        format.json { render :show, status: :ok, location: @follow }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /follows/1 or /follows/1.json
  def destroy
    @follow.destroy
    respond_to do |format|
      format.html { redirect_to follows_url, notice: 'User unfollowed successfully.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_follow
    @follow = Follow.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def follow_params
    params.require(:follow).permit(:user_id, :following_user_id)
  end

  def set_following
    @follow.following_user_id = params[:format]
  end
end

app/helpers/follows_helper.rb
# frozen_string_literal: true

module FollowsHelper
end

app/views/follows/_form.html.erb
<%= form_with(model: follow) do |form| %>
  <% if follow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(follow.errors.count, "error") %> prohibited this follow from being saved:</h2>

      <ul>
        <% follow.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<!-- 
  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>
-->
  <div class="field">
    <%= form.label :following_user_id %>
    <%= form.number_field :following_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/follows/edit.html.erb
<h1>Editing Follow</h1>

<%= render 'form', follow: @follow %>

<%= link_to 'Show', @follow %> |
<%= link_to 'Back', follows_path %>

app/views/follows/index.html.erb
<h1>My Followers</h1>
<table>
  <thead>
    <tr>
      <th>User</th>
      <!--<th>Following user</th>-->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @follows.each do |follow| %>
      <tr>
        <td><%= follow.user.name %></td>
        <!-- <td><%= follow.following_user_id %></td> -->
        <td><%= link_to 'View Profile', user_path(follow.user), html_options= {} %></td>
        <!-- <td><%= link_to 'Edit', edit_follow_path(follow) %></td> -->
        <td><%= link_to 'Reject', follow, method: :delete, data: { confirm: 'Are you sure that do you want to unfollow ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'New Follow', new_follow_path %> -->

<%= link_to "Add Followers", unfollowed_index_url %>


<br>
<br>
<%= link_to 'Back', landing_path %>

app/views/follows/new.html.erb
<h1>New Follow</h1>

<%= render 'form', follow: @follow %>

<%= link_to 'Back', unfollowed_index_url %>

app/views/follows/show.html.erb
<p>
  <strong>User:</strong>
  <%= @follow.user_id %>
</p>

<p>
  <strong>Following user:</strong>
  <%= @follow.following_user_id %>
</p>

<%= link_to 'Edit', edit_follow_path(@follow) %> |
<%= link_to 'Back', follows_path %>